version: "3.8"

volumes:
  pgdata:
  kongadata:

networks:
  kong-net:
    driver: bridge
  internal:

services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:2.0.4
    platform: linux/amd64
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "off"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga
    restart: always
    networks:
      - kong-net
    depends_on:
      - kong
    ports:
      - "1337:1337"
    volumes:
      - kongadata:/app/kongadata

  #################################
  # Frontend
  #################################
  frontend:
    image: sbrp/frontend:1.0
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - mysql-database
    networks:
      - internal
    restart: always
    ports:
      - "5173:5173"

  #################################
  # Database: MySQL
  #################################
  mysql-database:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    networks:
      - internal
    command: --init-file /init.sql
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./init.sql:/init.sql
      - ./data:/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_LOCAL_INFILE: "1"
    ports:
      - 3306:3306

  #################################
  # Database GUI: phpmyadmin
  #################################
  phpmyadmin:
    image: phpmyadmin:5.2.0
    depends_on:
      - mysql-database
    restart: always
    networks:
      - internal
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

  #################################
  # Staff: The Staff microservice
  #################################
  staff:
    image: sbrp/staff:1.0
    build:
      context: .
      dockerfile: backend/staff/Dockerfile
    depends_on:
      - mysql-database
    restart: always
    networks:
      - internal
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/staff

  #################################
  # Role Application: The Role Application microservice
  #################################
  application:
    image: sbrp/application:1.0
    build:
      context: .
      dockerfile: backend/application/Dockerfile
    depends_on:
      - mysql-database
    restart: always
    networks:
      - internal
    ports:
      - "5002:5002"
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/application
      staffURL: http://staff:5001/staff/
      roleURL: http://role:5003/role/

  #################################
  # Role: The Role microservice
  #################################
  role:
    image: sbrp/role:1.0
    build:
      context: .
      dockerfile: backend/role/Dockerfile
    depends_on:
      - mysql-database
    restart: always
    networks:
      - internal
    ports:
      - "5003:5003"
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/role

  #################################
  # Skill: The Skill microservice
  #################################
  skill:
    image: sbrp/skill:1.0
    build:
      context: .
      dockerfile: backend/skill/Dockerfile
    depends_on:
      - mysql-database
    restart: always
    networks:
      - internal
      - kong-net
    ports:
      - "5004:5004"
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/skill