version: "3.8"

networks:
  internal:

services:
  #################################
  # Frontend
  #################################
  frontend:
    image: mock-spm/frontend:1.0
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - mysql-database
    restart: always
    ports:
      - "3000:3000"

  #################################
  # Database: MySQL
  #################################
  mysql-database:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    networks:
      - internal
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  #################################
  # Database GUI: phpmyadmin
  #################################
  phpmyadmin:
    image: phpmyadmin:5.2.0
    depends_on:
      - mysql-database
    restart: always
    networks:
      - internal
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

  #################################
  # Staff: The Staff microservice
  #################################
  staff:
    image: mock-spm/staff:1.0
    build:
      context: .
      dockerfile: backend/staff/Dockerfile
    restart: always
    networks:
      - internal
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/staff

  #################################
  # Role: The Role microservice
  #################################
  role:
    image: mock-spm/role:1.0
    build:
      context: .
      dockerfile: backend/role/Dockerfile
    restart: always
    networks:
      - internal
    ports:
      - "5003:5003"
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/role
